# lihat file /etc/ansible/hosts di tag [ubuntua-server]
- hosts: gcloud-autralia-dua
  become: yes
  become_method: sudo
  tasks:
   - name: turn of the swaps
     shell: swapoff -a

   - name: create Docker config directory
     file: path=/etc/docker state=directory

   - name: changing Docker to systemd driver
     copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
        "exec-opts": ["native.cgroupdriver=systemd"]
        }
   
   - name: install containerd
     vars:
       ansible_python_interpreter: /usr/bin/python3
     apt:
       name: containerd
       state: present
  
   - name: install Docker
     vars:
       ansible_python_interpreter: /usr/bin/python3
     apt:
       name: docker.io
       state: present
       update_cache: true

   - name: install APT Transport HTTPS
     vars:
       ansible_python_interpreter: /usr/bin/python3
     apt:
       name: apt-transport-https
       state: present

   - name: add Kubernetes apt-key
     vars:
       ansible_python_interpreter: /usr/bin/python3
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: add Kubernetes' APT repository
     vars:
       ansible_python_interpreter: /usr/bin/python3
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   - name: install kubelet
     vars:
       ansible_python_interpreter: /usr/bin/python3
     apt:
       name: kubelet=1.23.4-00
       state: present
       update_cache: true

   - name: install kubeadm
     vars:
       ansible_python_interpreter: /usr/bin/python3
     apt:
       name: kubeadm=1.23.4-00
       state: present
       
   - name: install kubectl
     vars:
       ansible_python_interpreter: /usr/bin/python3
     apt:
       name: kubectl=1.23.4-00
       state: present
       force: yes

#error kubelet memang tak akan jalan pertama kali install
# nanti setelah melakukan perintah kubeadm shell baru akan jalan kubelet nya

# jika terdapat error di kubelet file /var/lib/kubelet/config.yml tidak di temukan
# eksekusi dengan perintah ini 
# kubeadm init phase kubelet-start
# kemudian jalankan kubeadm init  --pod-network-cidr=10.234.0.0/16  


#jika terdapat error unable load ca.cert
#cd /etc/kubernetes/pki
#openssl genrsa -out ca.key 2048
#openssl req -x509 -new -nodes -key ca.key -subj "/CN=139.99.171.75" -days 10000 -out ca.crt

# kubeadm join 139.99.171.75:6443 --token mqhiwn.hr5x2tqu859s0yf9 \
# --discovery-token-ca-cert-hash sha256:022afa7cfd28951ced323943d3eed5acfc2b114b0863db265283dc21d19971a7 