# lihat file /etc/ansible/hosts di tag [ubuntua-server]
- hosts: ovh
  become: yes
  become_method: sudo
  tasks:
   - name: turn of the swaps
     shell: swapoff -a

   - name: create Docker config directory
     file: path=/etc/docker state=directory

   - name: changing Docker to systemd driver
     copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
        "exec-opts": ["native.cgroupdriver=systemd"]
        }
   
   - name: install containerd
     vars:
       ansible_python_interpreter: /usr/bin/python2
     apt:
       name: containerd
       state: present
  
   - name: install Docker
     vars:
       ansible_python_interpreter: /usr/bin/python2
     apt:
       name: docker.io
       state: present
       update_cache: true

   - name: install APT Transport HTTPS
     vars:
       ansible_python_interpreter: /usr/bin/python2
     apt:
       name: apt-transport-https
       state: present

   - name: add Kubernetes apt-key
     vars:
       ansible_python_interpreter: /usr/bin/python2
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: add Kubernetes' APT repository
     vars:
       ansible_python_interpreter: /usr/bin/python2
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   - name: install kubelet
     vars:
       ansible_python_interpreter: /usr/bin/python2
     apt:
       name: kubelet=1.24.4-00
       state: present
       update_cache: true

   - name: install kubeadm
     vars:
       ansible_python_interpreter: /usr/bin/python2
     apt:
       name: kubeadm=1.24.4-00
       state: present
       
   - name: install kubectl
     vars:
       ansible_python_interpreter: /usr/bin/python2
     apt:
       name: kubectl=1.24.4-00
       state: present
       force: yes

# jika terdapat error di kubelet file /var/lib/kubelet/config.yml tidak di temukan
# eksekusi dengan perintah ini 
# kubeadm init phase kubelet-start
# kemudian jalankan kubeadm init  --pod-network-cidr=10.244.0.0/16  

# kubeadm join 192.168.88.250:6443 --token 2gpf1k.pw1f1446wvy58h5i \
# --discovery-token-ca-cert-hash sha256:7cc5ee5069df93e1ad658e2b67b2f71bb1360a588f99b718ebe4506103ad0d86