# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
# spec:
#   selector:
#     matchLabels:
#       app: nginx
#   replicas: 4 # tells deployment to run 2 pods matching the template
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1.14.2
#         ports:
#         - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-java
  namespace: default
  labels:
    account: test-java 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-java
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-java
      tier: test-java
  template:
    metadata:
      name: test-java
      labels:
        app: test-java
        tier: test-java
    spec:
      containers:
      - name: test-java
        image: docker.daunloker.com/spring-image:v1.0
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "1m"
        # args:
        # - -cpus
        # - "2"
        env:
        - name: MYSQL_USER
          value: "ian"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "mysql-root-user"
              key: "password"
        - name: HOST_DB
          value: "10.184.0.3:3306"  
        - name: MYSQL_DATABASE
          value: "springboot"   
        ports:
        - containerPort: 6060
      imagePullSecrets:
      - name: regcred

