apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: test-java
  ports:
    - port: 8080
      targetPort: 6060
  externalTrafficPolicy: Local
  externalIPs:
    - 34.116.93.116 
  type: LoadBalancer

# apiVersion: v1
# kind: Service
# metadata:
#   name: example-service
# spec:
#   type: NodePort
#   selector:
#       app: nginx
#   ports:
#       - port: 8080
#         targetPort: 80
#         nodePort: 30080
#   externalTrafficPolicy: Local